const { makeErrorMappingProxy } = require('@aragon/test-helpers/utils')

const errors = makeErrorMappingProxy({
  // aragonOS errors
  APP_AUTH_FAILED: 'APP_AUTH_FAILED',
  INIT_ALREADY_INITIALIZED: 'INIT_ALREADY_INITIALIZED',
  INIT_NOT_INITIALIZED: 'INIT_NOT_INITIALIZED',
  RECOVER_DISALLOWED: 'RECOVER_DISALLOWED',

  // Crowdfunding errors
  CROWDFUNDING_AUTH_FAILED: 'CROWDFUNDING_AUTH_FAILED',
  CROWDFUNDING_DAC_NOT_EXIST: 'CROWDFUNDING_DAC_NOT_EXIST',
  CROWDFUNDING_CAMPAIGN_NOT_EXIST: 'CROWDFUNDING_CAMPAIGN_NOT_EXIST',
  CROWDFUNDING_MILESTONE_NOT_EXIST:'CROWDFUNDING_MILESTONE_NOT_EXIST',
  CROWDFUNDING_EXCHANGE_RATE_NOT_EXISTS: 'CROWDFUNDING_EXCHANGE_RATE_NOT_EXISTS',
  CROWDFUNDING_TRANSFER_NOT_AUTHORIZED: 'CROWDFUNDING_TRANSFER_NOT_AUTHORIZED',
  CROWDFUNDING_DONATE_TOKEN_NOT_ENABLED: 'CROWDFUNDING_DONATE_TOKEN_NOT_ENABLED',
  CROWDFUNDING_TRANSFER_CAMPAIGN_NOT_BELONGS_DAC: 'CROWDFUNDING_TRANSFER_CAMPAIGN_NOT_BELONGS_DAC',
  CROWDFUNDING_TRANSFER_DONATION_NOT_BELONGS_BUDGET: 'CROWDFUNDING_TRANSFER_DONATION_NOT_BELONGS_BUDGET',
  CROWDFUNDING_MILESTONE_CANNOT_COMPLETE: 'CROWDFUNDING_MILESTONE_CANNOT_COMPLETE',
  CROWDFUNDING_MILESTONE_CANNOT_CANCEL: 'CROWDFUNDING_MILESTONE_CANNOT_CANCEL',

  CROWDFUNDING_WITHDRAW_NOT_APPROVED: 'CROWDFUNDING_WITHDRAW_NOT_APPROVED'
})

module.exports = {
  errors
}
